use crate::models::LessonItem;

pub fn get_seed_lessons() -> Vec<LessonItem> {
    vec![
        // ================= JAPANESE: BASIC HIRAGANA & STROKES =================
        LessonItem {
            id: "ja_hira_a".to_string(),
            language: "ja".to_string(),
            category: "alphabet".to_string(),
            target_text: "あ".to_string(),
            phonetic_or_kana: "a".to_string(),
            meaning_vi: "Chữ cái Hiragana: A".to_string(),
            workplace_context: "ありがとうございます (Arigatou gozaimasu)".to_string(),
            workplace_context_vi: "Cảm ơn quý khách/anh chị rất nhiều (câu cửa miệng trong môi trường làm việc)".to_string(),
            stroke_order_hints: vec![
                "Nét 1: Gạch ngang ngắn từ trái sang phải".to_string(),
                "Nét 2: Nét dọc hơi cong từ trên xuống cắt nét 1".to_string(),
                "Nét 3: Vòng tròn mở phía dưới bắt đầu từ trái cuộn sang phải".to_string(),
            ],
            difficulty_level: 1,
        },
        LessonItem {
            id: "ja_hira_i".to_string(),
            language: "ja".to_string(),
            category: "alphabet".to_string(),
            target_text: "い".to_string(),
            phonetic_or_kana: "i".to_string(),
            meaning_vi: "Chữ cái Hiragana: I".to_string(),
            workplace_context: "いいえ、大丈夫です (Iie, daijoubu desu)".to_string(),
            workplace_context_vi: "Không sao, tôi ổn/mọi thứ ổn".to_string(),
            stroke_order_hints: vec![
                "Nét 1: Nét cong bên trái, có móc nhẹ hất lên ở đuôi".to_string(),
                "Nét 2: Nét cong ngắn hơn bên phải hướng xuống".to_string(),
            ],
            difficulty_level: 1,
        },
        LessonItem {
            id: "ja_kata_bug".to_string(),
            language: "ja".to_string(),
            category: "it_workplace".to_string(),
            target_text: "バグ".to_string(),
            phonetic_or_kana: "bagu".to_string(),
            meaning_vi: "Lỗi phần mềm (Bug)".to_string(),
            workplace_context: "この機能に重大なバグが発生しました (Kono kinou ni juudai na bagu ga hassei shimashita)".to_string(),
            workplace_context_vi: "Chức năng này đã phát sinh một con bug nghiêm trọng.".to_string(),
            stroke_order_hints: vec![
                "Chữ バ (Ba): Viết nét ハ (Ha) rồi thêm 2 dấu phẩy đục âm ゛".to_string(),
                "Chữ グ (Gu): Viết nét ク (Ku) rồi thêm 2 dấu phẩy ゛".to_string(),
            ],
            difficulty_level: 1,
        },
        LessonItem {
            id: "ja_it_kaihatsu".to_string(),
            language: "ja".to_string(),
            category: "it_workplace".to_string(),
            target_text: "開発".to_string(),
            phonetic_or_kana: "かいはつ (kaihatsu)".to_string(),
            meaning_vi: "Phát triển (Development)".to_string(),
            workplace_context: "新しいシステムの開発チームに参加します (Atarashii shisutemu no kaihatsu chiimu ni sanka shimasu)".to_string(),
            workplace_context_vi: "Tôi sẽ tham gia vào đội ngũ phát triển hệ thống mới.".to_string(),
            stroke_order_hints: vec![
                "Chữ 開 (Khai): Bộ môn 門 bao ngoài, bên trong viết chữ khai".to_string(),
                "Chữ 発 (Phát): Viết bộ bát bên trên, sau đó các nét cung và phẩy bên dưới".to_string(),
            ],
            difficulty_level: 2,
        },
        LessonItem {
            id: "ja_it_shiyousho".to_string(),
            language: "ja".to_string(),
            category: "it_workplace".to_string(),
            target_text: "仕様書".to_string(),
            phonetic_or_kana: "しようしょ (shiyousho)".to_string(),
            meaning_vi: "Tài liệu đặc tả yêu cầu (Specification document)".to_string(),
            workplace_context: "仕様書を確認してから実装してください (Shiyousho wo kakunin shite kara jissou shite kudasai)".to_string(),
            workplace_context_vi: "Hãy đọc xác nhận tài liệu đặc tả trước khi bắt tay vào code.".to_string(),
            stroke_order_hints: vec![
                "Chữ 仕 (Sĩ): Bộ nhân đứng bên trái, chữ sĩ bên phải".to_string(),
                "Chữ 様 (Dạng): Bộ mộc bên trái, chữ dương bên phải".to_string(),
                "Chữ 書 (Thư): Các nét ngang song song, nét sổ giữa, bộ nhật bên dưới".to_string(),
            ],
            difficulty_level: 2,
        },
        LessonItem {
            id: "ja_it_kakunin".to_string(),
            language: "ja".to_string(),
            category: "it_workplace".to_string(),
            target_text: "確認".to_string(),
            phonetic_or_kana: "かくにん (kakunin)".to_string(),
            meaning_vi: "Kiểm tra, xác nhận (Check / Confirm)".to_string(),
            workplace_context: "プルリクエストのご確認をお願いします (Puru rikuesuto no gokakunin wo onegai shimasu)".to_string(),
            workplace_context_vi: "Nhờ anh/chị kiểm tra giúp em cái Pull Request này nhé ạ.".to_string(),
            stroke_order_hints: vec![
                "Chữ 確 (Xác): Bộ thạch bên trái, chữ hạc bên phải".to_string(),
                "Chữ 認 (Nhận): Bộ ngôn bên trái, chữ nhẫn bên phải".to_string(),
            ],
            difficulty_level: 2,
        },

        // ================= ENGLISH: FOUNDATIONAL & IT WORKPLACE =================
        LessonItem {
            id: "en_it_deploy".to_string(),
            language: "en".to_string(),
            category: "it_workplace".to_string(),
            target_text: "deploy".to_string(),
            phonetic_or_kana: "/dɪˈplɔɪ/".to_string(),
            meaning_vi: "Triển khai hệ thống/phần mềm lên server".to_string(),
            workplace_context: "We are ready to deploy the release to production tonight.".to_string(),
            workplace_context_vi: "Chúng tôi đã sẵn sàng triển khai phiên bản mới lên môi trường production tối nay.".to_string(),
            stroke_order_hints: vec![
                "Viết thường 'd-e-p-l-o-y'".to_string(),
                "Chú ý nét đuôi chữ 'p' và 'y' kéo xuống dưới dòng kẻ".to_string(),
            ],
            difficulty_level: 1,
        },
        LessonItem {
            id: "en_it_deadline".to_string(),
            language: "en".to_string(),
            category: "it_workplace".to_string(),
            target_text: "deadline".to_string(),
            phonetic_or_kana: "/ˈded.laɪn/".to_string(),
            meaning_vi: "Hạn chót, thời hạn hoàn thành công việc".to_string(),
            workplace_context: "Can we extend the deadline for this sprint task by two days?".to_string(),
            workplace_context_vi: "Chúng ta có thể gia hạn thời hạn nhiệm vụ sprint này thêm hai ngày được không?".to_string(),
            stroke_order_hints: vec![
                "Viết thường 'd-e-a-d-l-i-n-e'".to_string(),
                "Nối các ký tự liền mạch để ghi nhớ từ vựng theo cụm chữ cái".to_string(),
            ],
            difficulty_level: 1,
        },
        LessonItem {
            id: "en_it_resolve".to_string(),
            language: "en".to_string(),
            category: "it_workplace".to_string(),
            target_text: "resolve".to_string(),
            phonetic_or_kana: "/rɪˈzɑːlv/".to_string(),
            meaning_vi: "Giải quyết triệt để (vấn đề, bug, ticket)".to_string(),
            workplace_context: "I will investigate and resolve the API timeout issue before lunch.".to_string(),
            workplace_context_vi: "Tôi sẽ điều tra và xử lý dứt điểm sự cố timeout của API trước giờ ăn trưa.".to_string(),
            stroke_order_hints: vec![
                "Viết thường 'r-e-s-o-l-v-e'".to_string(),
            ],
            difficulty_level: 1,
        },
        LessonItem {
            id: "en_it_requirement".to_string(),
            language: "en".to_string(),
            category: "it_workplace".to_string(),
            target_text: "requirement".to_string(),
            phonetic_or_kana: "/rɪˈkwaɪər.mənt/".to_string(),
            meaning_vi: "Yêu cầu kỹ thuật, yêu cầu nghiệp vụ của dự án".to_string(),
            workplace_context: "The client changed the authentication requirement in the latest meeting.".to_string(),
            workplace_context_vi: "Khách hàng đã thay đổi yêu cầu phần xác thực trong cuộc họp gần nhất.".to_string(),
            stroke_order_hints: vec![
                "Viết 'r-e-q-u-i-r-e-m-e-n-t'".to_string(),
                "Phân tách: require + ment".to_string(),
            ],
            difficulty_level: 2,
        },
        LessonItem {
            id: "en_it_incident".to_string(),
            language: "en".to_string(),
            category: "it_workplace".to_string(),
            target_text: "incident".to_string(),
            phonetic_or_kana: "/ˈɪn.sɪ.dənt/".to_string(),
            meaning_vi: "Sự cố kỹ thuật đột xuất, gián đoạn dịch vụ".to_string(),
            workplace_context: "The on-call team responded to the database incident within 5 minutes.".to_string(),
            workplace_context_vi: "Đội ngũ trực on-call đã phản hồi sự cố cơ sở dữ liệu trong vòng 5 phút.".to_string(),
            stroke_order_hints: vec![
                "Viết thường 'i-n-c-i-d-e-n-t'".to_string(),
            ],
            difficulty_level: 2,
        },
    ]
}
